### PR TITLE
Add Andalusia region (AN) holidays

### PR DESCRIPTION
**Pull request by vice**
Some of these holidays could be celebrated in others regions of Spain. At least they are correct for Andalusia region (AN).

### CODE REVIEW

**Comment by lauft** [comment]
Thanks for your contribution! 👍 
Can you provide the online sources which define these holidays (official legal documents preferred). This will help to check on updates in the future.

**Comment by vice** [comment]
I used those references
https://administracion.gob.es/pag_Home/atencionCiudadana/calendarios/laboral.html
http://www.seg-social.es/wps/portal/wss/internet/CalendarioLaboral
https://es.wikipedia.org/wiki/Calendario_laboral (Not official but accurate)

For Andalusia
https://www.juntadeandalucia.es/temas/trabajar/relaciones/calendario.html

Also checked https://www.calendarioslaborales.com/ they could be used to check holidays in other Spanish regions and locations but is not an official source and could contain errors.

**Comment by vice** [comment]
In the first references you can find this legal document https://www.boe.es/diario_boe/txt.php?id=BOE-A-2019-14552
But this is just for 2020.

**Comment by vice** [comment]
In Spain is very common to have Moday holidays when a fixed one is on Sunday but it is a regional decision. I added those that Andalusia region accept as far as I have researched. I think there would many other regions included but it need to be checked.

**Comment by vice** [comment]
I probably will do more addition and correction from official documents. Including for other regions besides Andalusia.

**Comment by vice** [comment]
I think I pushed a change in the middle of the checks. I check it later.

**Comment by vice** [comment]
I see, I need to check tests because I changed names and remove some days. I will do another day.

**Comment by lauft** [comment]
> I see, I need to check tests because I changed names and remove some days. I will do later.

You most probably will need to update the snapshots by calling
```
pytest test/test_holidata.py --snapshot-update
```

**Comment by vice** [comment]
Thanks for the tip. I'm going to close this pull request a prepare a new one updating code and tests snapshots.

**Pull request closed without merging**
